import { Toaster } from 'react-hot-toast';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import { QueryProvider } from '@/components/QueryWrapper';
import { SocketProvider } from '@/hooks/SocketContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AlgoJourney",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >   

        <QueryProvider>     
        <SessionProviderWrapper>
        <SocketProvider>
        <header className="absolute w-full"><Navbar/></header>
        <main className="w-full flex justify-center min-h-screen relative"> {/* Changed from overflow-hidden to relative */}
  <div className="w-full relative"> {/* Added relative positioning */}
    {children}
    <Toaster />
  </div>
</main>
        </SocketProvider>
        </SessionProviderWrapper>
        </QueryProvider>


      </body>
      
    </html>

  );
}
